### ISSUE TITLE
Can you use actual output instead of file?

### ISSUE THREAD

**Issue by robertiagar** [black/Music-Visualization#1]
Instead of 
` 
minim = new Minim(this);
player = minim.loadFile("D:/Cisum/Ragni MMS 2/Baby Doll - Ragini MMS 2 - [SongsPk.CC].mp3");
meta = player.getMetaData();
`

I tried using:
`
player = minim.getLineOut();
`

but the visualizer is not responding.  Any idea why? I've also change the `player` type from `AudioPlayer` to `AudioOutput`.

Sorry I made an issue, but it was the only way to ask you something 😄 

Great work on the visualizer 👍

**Comment by black** [comment]
Hey, I am really sorry but I didn't get your question. Would you mind explaining a bit ?

**Comment by robertiagar** [comment]
Instead of loading a file from the disk, I want to use the system Audio Output. Can it be done?

**Comment by black** [comment]
Hey try this - https://processing.org/discourse/beta/num_1229300351.html

**Comment by robertiagar** [comment]
Ah yes. I forgot about this in processing. Will try to see if it works. Will close the issue. Thank you and again, great Visualizer 😉
